; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Generic build selector:
; Change ONLY this line to choose what to build from src/
; Examples:
;   build_src_filter = +<i2c_scanner_devices.cpp>
;   build_src_filter = +<sensors.cpp>
build_src_filter = +<sensors.cpp>

; Keep commonly used libraries here so switching src_filter works without editing deps each time.
lib_deps =
  phzi/DFRobot_MultiGasSensor@^2.0.0
  adafruit/Adafruit MS8607
  adafruit/Adafruit Unified Sensor
  dfrobot/DFRobot_MLX90614
  starmbi/hp_BH1750
  claws/BH1750
  dfrobot/DFRobot_Alcohol
  dfrobot/DFRobot_MHZ9041A
